version: "3.7"

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    networks: 
      AIservice: 
        aliases: 
          - frontend.docker
    depends_on:
      - backend
    volumes:
        - ./frontend:/app
        - ./storage:/storage

  backend:
    build: backend
    ports:
      - 8000:8000
    networks: 
      AIservice: 
        aliases: 
          - backend.docker
    volumes:
      - ./backend:/app
      - ./storage:/storage

  orion-ld:
    image: fiware/orion-ld
    container_name: fiware-orion-ld
    networks: 
      AIservice: 
        aliases: 
          - orion.docker
    expose:
      - "1026"
    ports:
      - "1027:1026"
    depends_on:
      - mongo-database
    command: -dbhost mongo-db -logLevel DEBUG

  mongo-database:
    image: mongo:3.6
    container_name: database-mongo
    networks: 
      AIservice: 
        aliases: 
          - mongo.docker
    command: --nojournal
    volumes:
      - mongo-database:/database

networks:
  AIservice:
    external: true
volumes:
  mongo-database: ~
